cache:
  mount:
    - node_modules
    - .git

build:
  main:
    image: newcrossfoodcoop/nxfc_base:latest-drone
    commands:
      - npm install
      - gulp build
      - gulp test
      - gulp test:express &
      - sleep 10s
      - NODE_ENV=test abao provides/express/raml/api.raml --server http://localhost:3041/api --hookfiles=provides/express/raml/hooks/*.js

compose:
  mongo:
    image: mongo:3

publish:
      
  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc_stock
    tag: latest
    file: Dockerfile.prod
    when:
      branch: master

  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc_stock
    tag: $$TAG
    file: Dockerfile.prod
    when:
      event: tag
