version: '2'
services:
  mongo:
    image: "mongo:3.0"
    ports:
      - "27017:27017"
  stock:
    network_mode: host
    build: .
    ports:
      - "3041:3041"
    depends_on:
      - mongo
    command: gulp test:express
    environment:
      - DEBUG=provides:express:*
  catalogue:
    network_mode: host
    image: newcrossfoodcoop/nxfc_catalogue:latest
    ports:
      - "3011:3011"
    depends_on:
      - mongo
    command: gulp test:api
  checkout:
    network_mode: host
    image: newcrossfoodcoop/nxfc_base:latest-drone
    ports:
      - "3031:3031"
    volumes:
      - "./depends/checkout:/home/app/depends/checkout" 
    command: osprey-mock-service -f depends/checkout/raml/api.raml -p 3031
