version: '2'
services:
  mongo:
    image: "mongo:3.0"
    ports:
      - "27017:27017"
  stock:
    network_mode: host
    build: .
    ports:
      - "3041:3041"
    depends_on:
      - mongo
    command: gulp test:express
