version: '2'
services:
  mongo:
    image: "mongo:3.0"
    ports:
      - "27017:27017"
  stock:
    build: .
    volumes:
      - "./depends:/home/app/depends"
      - "./provides:/home/app/provides"
    ports:
      - "3040:3040"
      - "5858:5858"
    depends_on:
      - mongo
    environment:
      - MONGO_HOSTNAME=mongo
      - DEBUG=provides:express
    command: gulp
